# Test CI pipeline

image: golang:latest

stages:
  - build
  - test

compile:
  stage: build
  script:
  - echo "Building auditlog microservice!" 
    - cd src
    - mkdir -p bin
    - go mod download && go mod tidy
    - go build -o auditlog.exe
  artifacts:
    paths:
      - src/auditlog.exe

test:
  stage: test
  script: 
    - echo "Testing auditlog microservice!" 
    - go test ./... -v
