openapi: 3.0.0
info:
  title: Audit Log API
  version: 1.0.0
paths:
  /events/submit:
    post:
      summary: Submit an event
      description: |
        This endpoint allows clients to submit an audit log event.

        The request body should contain the event data in JSON format.

        Upon successful submission, the event will be decoded, saved, and logged.

      responses:
        '200':
          description: Event submitted successfully
        '400':
          description: Invalid event data

  /events/query:
    get:
      summary: Query events
      description: |
        This endpoint allows clients to query events based on query parameters.

        The query parameters should be provided in the URL.

        The response will contain a JSON array of unique events matching the query.

      responses:
        '200':
          description: Query successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '500':
          description: Error retrieving or encoding events

  /generatetoken:
    get:
      summary: Generate JWT token
      description: |
        This endpoint generates a JWT token with a specified expiry time and additional claims if needed.

        The token is signed using the HS256 signing method and the configured secret key.

      responses:
        '200':
          description: Token generated successfully
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Error generating authentication token
components:
  schemas:
    Event:
      type: object
      properties:
        EventID:
          type: string
          description: Event Unique ID generated by the audit log
        Timestamp:
          type: string
          format: date-time
          description: Timestamp in nanoseconds of the moment the audit log received the event
        SourceEventID:
          type: string
          description: Event ID provided by the source service
        SourceTimestamp:
          type: string
          format: date-time
          description: Timestamp in nanoseconds provided by the source service
        CorrelationID:
          type: string
          description: Event correlation ID in case other events are related
        SourceTimezone:
          type: string
          description: Timezone of the source service
        SourceServiceName:
          type: string
          description: Name of the source service
        SourceServiceLocation:
          type: string
          description: Source service geographical information
        SourceIPAddress:
          type: string
          description: Source service IP address
        EventTags:
          type: object
          additionalProperties:
            type: string
          description: Event metadata
        EventDataHash:
          type: string
          description: Event data hash or checksum for integrity
        EventDataVersion:
          type: string
          description: Event data version
        EventData:
          type: object
          additionalProperties: true
          description: Various event data depending on their type
